
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/umc1stweekMission
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true